from .supervised_learning.perceptron import Perceptron
from .supervised_learning.linear_regression import LinearRegression
from .supervised_learning.logistic_regression import LogisticRegression
from .supervised_learning.k_nearest_neightbors import KNN